#!/usr/bin/env python3
"""Build the static Mchel Speedrun Rating website.

Inputs are generated by scripts/mchel_time_attack_rating_v1.py.  The output is a
plain HTML/CSS/JavaScript site that can be published from docs/ on GitHub
Pages.

Example:
  python build_site.py \
      --overall-csv work/rating/overall_ranking.csv \
      --components-csv work/rating/best30_components.csv \
      --metadata-json work/rating/rating_metadata.json \
      --snapshot-summary work/latest/mchel_1_12_2_run_summary_excluding_seasonal.json \
      --out-dir docs
"""
from __future__ import annotations

import argparse
import csv
import html
import json
import shutil
from collections import defaultdict
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any
from urllib.parse import quote

JST = timezone(timedelta(hours=9), name="JST")
SITE_TITLE = "ちぇる鯖アスレチック 総合レートランキング"
SITE_DESCRIPTION = "Mchel 1.12.2アスレチックの公開スピードランランキングから算出した、非公式の総合レートランキング。"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build static Mchel rating pages.")
    parser.add_argument("--overall-csv", type=Path, required=True)
    parser.add_argument("--components-csv", type=Path, required=True)
    parser.add_argument("--metadata-json", type=Path, required=True)
    parser.add_argument("--snapshot-summary", type=Path, default=None)
    parser.add_argument("--out-dir", type=Path, default=Path("docs"))
    return parser.parse_args()


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def escape(value: Any) -> str:
    return html.escape(str(value), quote=True)


def float_value(value: str | None, fallback: float = 0.0) -> float:
    try:
        return float(value or fallback)
    except (TypeError, ValueError):
        return fallback


def int_value(value: str | None, fallback: int = 0) -> int:
    try:
        return int(float(value or fallback))
    except (TypeError, ValueError):
        return fallback


def format_time(ms: int) -> str:
    minutes, remainder = divmod(ms, 60_000)
    seconds, millis = divmod(remainder, 1_000)
    return f"{minutes}:{seconds:02d}.{millis:03d}"


def format_jst(value: str | None) -> str:
    if not value:
        return "取得日時不明"
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
        if parsed.tzinfo is None:
            parsed = parsed.replace(tzinfo=timezone.utc)
        return parsed.astimezone(JST).strftime("%Y年%-m月%-d日 %H:%M JST")
    except ValueError:
        return escape(value)


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def unofficial_notice() -> str:
    return """
<div class="unofficial-notice" role="note">
  <div class="notice-inner">
    <strong>非公式</strong>
    <span>Mchel公式とは関係ありません。</span>
  </div>
</div>
"""


def unofficial_chip(compact: bool = False) -> str:
    cls = "unofficial-chip compact" if compact else "unofficial-chip"
    return f'<div class="{cls}"><b>非公式</b></div>'


def nav(current: str = "") -> str:
    def link(href: str, label: str, key: str) -> str:
        cls = "nav-link active" if current == key else "nav-link"
        return f'<a class="{cls}" href="{href}">{label}</a>'

    return f"""
<header class="site-header">
  <div class="header-inner">
    <a class="brand" href="index.html" aria-label="トップへ">
      <span class="brand-mark">M</span>
      <span><strong>Mchel Speedrun Rating</strong><small>1.12.2 Athletic</small></span>
    </a>
    <nav class="main-nav" aria-label="メインナビゲーション">
      {link('index.html', '総合ランキング', 'ranking')}
      {link('about.html', 'レートについて', 'about')}
    </nav>
  </div>
</header>
"""


def footer(updated: str) -> str:
    return f"""
<footer class="site-footer">
  <div class="footer-inner">
    <p>非公式サイトです。記録データは公開ランキングAPIをもとに集計しています。</p>
    <p>最終データ取得：<time>{escape(updated)}</time></p>
  </div>
</footer>
"""


def page_shell(
    title: str,
    body: str,
    updated: str,
    current: str = "",
    depth: int = 0,
    description: str = "",
) -> str:
    prefix = "../" * depth
    header = (
        nav(current)
        .replace('href="index.html"', f'href="{prefix}index.html"')
        .replace('href="about.html"', f'href="{prefix}about.html"')
    )
    desc = description or SITE_DESCRIPTION
    return f"""<!doctype html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="{escape(desc)}">
  <meta name="robots" content="index,follow">
  <title>{escape(title)} | {SITE_TITLE}</title>
  <link rel="stylesheet" href="{prefix}static/style.css">
  <script defer src="{prefix}static/app.js"></script>
</head>
<body>
{unofficial_notice()}
{header}
<main>
{body}
</main>
{footer(updated)}
</body>
</html>
"""


def tier_class(tier: str) -> str:
    """Return a CSS-safe class suffix for tiers such as B+, B-, and C-."""
    normalized = tier.lower().replace("+", "plus").replace("-", "minus")
    return "".join(ch for ch in normalized if ch.isalnum()) or "unknown"


def tier_badge(tier: str) -> str:
    return f'<span class="tier tier-{tier_class(tier)}">{escape(tier)}</span>'


def player_page_url(player_name: str) -> str:
    return "https://www.mchel.net/player/" + quote(player_name, safe="_-.")


def course_ranking_url(course_name: str) -> str:
    fragment = "athletic-1.12.2:ranking:" + quote(course_name, safe="")
    return "https://www.mchel.net/info#" + fragment


def build_index(overall: list[dict[str, str]], metadata: dict[str, Any], updated: str) -> str:
    player_count = len(overall)
    course_count = metadata.get("eligible_course_count", "—")
    top_rating = float_value(overall[0].get("published_rating")) if overall else 0.0

    rows: list[str] = []
    for player in overall:
        uuid = player["player_uuid"]
        rank = int_value(player.get("overall_rank"))
        rating = float_value(player.get("published_rating"))
        rows.append(
            f"""
<tr data-player-row data-name="{escape(player.get('player_name', '')).lower()}" data-tier="{escape(player.get('tier', ''))}" data-rank="{rank}">
  <td class="rank-cell">{rank}</td>
  <td class="player-cell"><a href="players/{escape(uuid)}.html">{escape(player.get('player_name', ''))}</a></td>
  <td>{tier_badge(player.get('tier', ''))}</td>
  <td class="rating-cell">{rating:,.2f}</td>
  <td>{int_value(player.get('eligible_course_count'))}</td>
  <td>{float_value(player.get('best_course_score')):.3f}</td>
  <td>{float_value(player.get('thirtieth_course_score')):.3f}</td>
</tr>"""
        )

    tier_options = "".join(
        f'<option value="{tier}">{tier}</option>'
        for tier in ["EX", "S+", "S", "A+", "A", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "E"]
    )
    body = f"""
<section class="hero">
  <div class="container hero-grid">
    <div class="hero-content">
      {unofficial_chip()}
      <p class="eyebrow">Mchel 1.12.2 SPEEDRUN · RATING V1</p>
      <h1 class="hero-title">
        <span class="hero-title-line title-main">ちぇる鯖アスレチック</span>
        <span class="hero-title-line title-sub">総合レートランキング</span>
      </h1>
      <p class="hero-copy">1.12.2の公開スピードラン記録をもとに、1位難易度を加味してプレイヤーごとの上位30コースを評価した非公式総合ランキングです。</p>
      <div class="hero-actions">
        <a class="button primary" href="#ranking">ランキングを見る</a>
        <a class="button ghost" href="about.html">算出方法</a>
      </div>
    </div>
    <aside class="hero-card" aria-label="集計概要">
      <p class="card-kicker">CURRENT SNAPSHOT</p>
      <div class="stat-grid">
        <div><strong>{player_count}</strong><span>公式対象プレイヤー</span></div>
        <div><strong>{course_count}</strong><span>対象コース</span></div>
        <div><strong>{top_rating:,.0f}</strong><span>最高レート</span></div>
        <div><strong>30</strong><span>採用コース数</span></div>
      </div>
      <p class="small-muted">更新：{escape(updated)}</p>
    </aside>
  </div>
</section>
<section class="container section" id="ranking">
  <div class="section-heading">
    <div>
      <p class="eyebrow">LEADERBOARD</p>
      <h2>総合ランキング</h2>
      <p>プレイヤー名をクリックすると、採用された上位30コースの詳細を見られます。</p>
    </div>
    <span id="visible-count" class="result-count">{player_count} 人表示中</span>
  </div>
  <div class="filter-bar" aria-label="ランキング検索">
    <label class="search-field"><span class="sr-only">プレイヤー名で検索</span><input id="player-search" type="search" placeholder="プレイヤー名で検索"></label>
    <label class="select-field"><span class="sr-only">Tierで絞り込み</span><select id="tier-filter"><option value="">全Tier</option>{tier_options}</select></label>
    <button id="clear-filters" class="button small" type="button">絞り込みを解除</button>
  </div>
  <div class="table-wrap">
    <table class="ranking-table">
      <thead><tr><th>順位</th><th>プレイヤー</th><th>Tier</th><th>レート</th><th>対象コース<br>ランクイン数</th><th>最高<br>補正スコア</th><th>上位30コース<br>最低補正スコア</th></tr></thead>
      <tbody>{''.join(rows)}</tbody>
    </table>
  </div>
  <p class="table-note">対象コースは、取得時点で上位100件が埋まっているコースです。ランキング外は未挑戦か101位以下かを判別できないため、減点には使用していません。</p>
</section>
"""
    return page_shell("総合ランキング", body, updated, current="ranking")


def component_rank(comp: dict[str, str]) -> str:
    rank = int_value(comp.get("rank"))
    return f"#{rank}" if rank > 0 else "—"


def adjusted_score(comp: dict[str, str]) -> float:
    return float_value(comp.get("difficulty_adjusted_course_score"))


def weighted_contribution(comp: dict[str, str]) -> float:
    return float_value(comp.get("weighted_contribution"))


def build_player_page(player: dict[str, str], components: list[dict[str, str]], updated: str) -> str:
    rank = int_value(player.get("overall_rank"))
    rating = float_value(player.get("published_rating"))
    all_count = int_value(player.get("eligible_course_count"))
    ordered_components = sorted(components, key=lambda c: int_value(c.get("best30_position")))
    average_course_score = (
        sum(adjusted_score(comp) for comp in ordered_components) / len(ordered_components)
        if ordered_components
        else 0.0
    )
    first_place_count = sum(int_value(comp.get("rank")) == 1 for comp in ordered_components)

    records: list[str] = []
    for comp in ordered_components:
        course = comp.get("course_name", "")
        ranking_url = course_ranking_url(course)
        records.append(
            f"""
<tr>
  <td>{int_value(comp.get('best30_position'))}</td>
  <td><a href="{escape(ranking_url)}" target="_blank" rel="noopener noreferrer">{escape(course)}</a></td>
  <td class="course-rank">{component_rank(comp)}</td>
  <td>{format_time(int_value(comp.get('time_ms')))}</td>
  <td>{format_time(int_value(comp.get('course_record_time_ms')))}</td>
  <td>{float_value(comp.get('first_place_difficulty')):.3f}</td>
  <td>{float_value(comp.get('difficulty_multiplier')):.3f}×</td>
  <td>{adjusted_score(comp):.3f}</td>
  <td>{float_value(comp.get('weight')):.3f}</td>
  <td>{weighted_contribution(comp):.3f}</td>
</tr>"""
        )

    uuid = player["player_uuid"]
    mchel_profile_url = player_page_url(player.get("player_name", ""))
    body = f"""
<section class="player-hero">
  <div class="container">
    <a class="back-link" href="../index.html">← 総合ランキングへ戻る</a>
    <div class="player-heading">
      <div>
        {unofficial_chip(compact=True)}
        <p class="eyebrow">PLAYER PROFILE</p>
        <h1>{escape(player.get('player_name', ''))}</h1>
        <a class="player-link" href="{escape(mchel_profile_url)}" target="_blank" rel="noopener noreferrer">Mchelの個人ページを開く</a>
        <p class="uuid">UUID: <code>{escape(uuid)}</code></p>
      </div>
      <div class="hero-rating">
        {tier_badge(player.get('tier', ''))}
        <strong>{rating:,.2f}</strong>
        <span>総合 {rank} 位</span>
      </div>
    </div>
    <div class="profile-stats">
      <div><span>対象コース<br>ランクイン数</span><strong>{all_count}</strong></div>
      <div><span>最高<br>補正スコア</span><strong>{float_value(player.get('best_course_score')):.3f}</strong></div>
      <div><span>上位30コース<br>最低補正スコア</span><strong>{float_value(player.get('thirtieth_course_score')):.3f}</strong></div>
      <div><span>上位30コース<br>平均補正スコア</span><strong>{average_course_score:.3f}</strong></div>
      <div><span>採用コースの<br>1位回数</span><strong>{first_place_count}</strong></div>
    </div>
  </div>
</section>
<section class="container section">
  <div class="section-heading compact">
    <div>
      <p class="eyebrow">TOP 30 COURSES</p>
      <h2>上位30コース</h2>
      <p>総合レートの計算に採用された記録です。コース名からMchelのランキング画面を開けます。</p>
    </div>
  </div>
  <div class="table-wrap">
    <table class="components-table">
      <thead><tr><th>採用順位</th><th>コース</th><th>コース順位</th><th>自分のタイム</th><th>1位タイム</th><th>1位<br>難易度</th><th>難易度<br>倍率</th><th>補正<br>スコア</th><th>重み</th><th>重み付き<br>寄与</th></tr></thead>
      <tbody>{''.join(records)}</tbody>
    </table>
  </div>
  <div class="info-panel">
    <h3>このレートについて</h3>
    <p>総合レートは、対象コースで30件以上ランクインしたプレイヤーだけに表示されます。詳しい計算条件は<a href="../about.html">レートについて</a>をご覧ください。</p>
  </div>
</section>
"""
    return page_shell(
        f"{player.get('player_name', '')} の個人ページ",
        body,
        updated,
        depth=1,
        description=f"{player.get('player_name', '')} のMchel 1.12.2アスレチック総合レートと上位30コース。",
    )


def build_about(metadata: dict[str, Any], updated: str) -> str:
    course_count = metadata.get("eligible_course_count", "—")
    scoring = metadata.get("scoring", {})
    best_n = int_value(str(scoring.get("best_n", 30)), 30)
    formula_version = metadata.get("formula_version", "mchel_time_attack_rating_v1")
    difficulty_version = metadata.get("difficulty_version", "—")
    tiers = metadata.get("tier_counts", {})
    tier_text = ", ".join(f"{key} {value}人" for key, value in tiers.items())
    theoretical = metadata.get("catalog_constrained_theoretical_max", {})
    theoretical_rating = float_value(str(theoretical.get("published_rating", 0)))

    body = f"""
<section class="subhero">
  <div class="container">
    {unofficial_chip(compact=True)}
    <p class="eyebrow">METHODOLOGY · RATING V1</p>
    <h1>レートについて</h1>
    <p>公開スピードランランキングを、コースごとの1位難易度を加味して比較する総合レートです。</p>
  </div>
</section>
<section class="container section prose">
  <div class="method-grid">
    <article class="method-card"><span>01</span><h2>対象コース</h2><p>取得時点でランキングが上位100件まで埋まっているコースだけを対象にします。現在の対象は <strong>{escape(course_count)}コース</strong> です。</p></article>
    <article class="method-card"><span>02</span><h2>基本スコア</h2><p>各コースの1位タイムを100点とし、<code>100 × 1位タイム ÷ 自分のタイム</code> で評価します。1位記録は100点です。</p></article>
    <article class="method-card"><span>03</span><h2>1位難易度</h2><p>1位の突出度と、2〜10位の密集度をカタログ内で比較し、両方が高いコースほど評価を上乗せします。倍率は <code>1 + 0.10 × 難易度</code> です。</p></article>
    <article class="method-card"><span>04</span><h2>上位{best_n}コース</h2><p>対象コースへのランクインが {best_n}件以上のプレイヤーが正式レート対象です。各人の補正スコアが高い {best_n}コースだけを採用します。</p></article>
    <article class="method-card"><span>05</span><h2>重み付き平均</h2><p>採用コースは上位側を少し重くしつつ、30位の記録も評価します。重みは1位=1.00、30位=0.50です。</p></article>
    <article class="method-card"><span>06</span><h2>公開レート</h2><p>生の実力指数Pを2段階の変換で公開レートにします。P=100はレート1000、理論上の数式上限は1600です。</p></article>
  </div>
  <h2>ランク</h2>
  <div class="tier-explainer tier-explainer-v1">
    <div><b>EX</b><span>1300–1600</span></div><div><b>S+</b><span>1250–1299.99</span></div><div><b>S</b><span>1200–1249.99</span></div><div><b>A+</b><span>1150–1199.99</span></div><div><b>A</b><span>1100–1149.99</span></div><div><b>B+</b><span>1050–1099.99</span></div><div><b>B</b><span>1000–1049.99</span></div><div><b>B-</b><span>950–999.99</span></div><div><b>C+</b><span>900–949.99</span></div><div><b>C</b><span>850–899.99</span></div><div><b>C-</b><span>800–849.99</span></div><div><b>D+</b><span>750–799.99</span></div><div><b>D</b><span>700–749.99</span></div><div><b>E</b><span>100–699.99</span></div>
  </div>
  <p class="small-muted">現在の対象者内訳：{escape(tier_text)}</p>
  <h2>カタログ制約付き理論最大値</h2>
  <p>現在の難易度表で難易度が高い30コースすべてを1位で走った場合の理論値は <strong>{theoretical_rating:,.2f}</strong> です。新コース追加や難易度表の更新時には変動します。</p>
  <h2>重要な注意</h2>
  <ul>
    <li>データは各コースの公開ランキング上位100件のみです。ランキング外は未挑戦と101位以下を区別できないため、未掲載を減点には使いません。</li>
    <li>期間限定アスレチックは対象外です。</li>
    <li>1位難易度は、コース全体の難しさではなく「1位に近い記録を出す難しさ」を表す指標です。</li>
    <li>難易度表は日ごとに変えず、月次またはコース追加・改変時に見直す想定です。</li>
    <li>これは非公式の集計です。元データの正確性、ゲーム内の公式評価、プレイヤーの総合的な実力を保証するものではありません。</li>
  </ul>
  <p class="updated-callout">数式バージョン：<code>{escape(formula_version)}</code><br>難易度表：<code>{escape(difficulty_version)}</code><br>現在のデータ取得日時：{escape(updated)}</p>
</section>
"""
    return page_shell("レートについて", body, updated, current="about")


def copy_static_assets(project_root: Path, out_dir: Path) -> None:
    static_src = project_root / "static"
    static_dest = out_dir / "static"
    if not static_src.exists():
        raise FileNotFoundError(f"Static asset directory not found: {static_src}")
    if static_dest.exists():
        shutil.rmtree(static_dest)
    shutil.copytree(static_src, static_dest)


def main() -> int:
    args = parse_args()
    for path in [args.overall_csv, args.components_csv, args.metadata_json]:
        if not path.exists():
            raise FileNotFoundError(f"Input file not found: {path}")

    overall = read_csv(args.overall_csv)
    components = read_csv(args.components_csv)
    metadata = json.loads(args.metadata_json.read_text(encoding="utf-8"))
    snapshot: dict[str, Any] = {}
    if args.snapshot_summary and args.snapshot_summary.exists():
        snapshot = json.loads(args.snapshot_summary.read_text(encoding="utf-8"))
    updated = format_jst(
        snapshot.get("source_run_fetched_at_utc") or snapshot.get("fetched_at_utc")
    )

    components_by_uuid: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in components:
        components_by_uuid[row["player_uuid"]].append(row)

    out = args.out_dir
    if out.exists():
        shutil.rmtree(out)
    (out / "players").mkdir(parents=True, exist_ok=True)
    copy_static_assets(Path(__file__).resolve().parent, out)

    write_text(out / "index.html", build_index(overall, metadata, updated))
    write_text(out / "about.html", build_about(metadata, updated))
    for player in overall:
        uuid = player["player_uuid"]
        write_text(
            out / "players" / f"{uuid}.html",
            build_player_page(player, components_by_uuid.get(uuid, []), updated),
        )

    manifest = {
        "title": SITE_TITLE,
        "updated": updated,
        "player_count": len(overall),
        "player_page_count": len(overall),
        "rating_metadata": metadata,
    }
    write_text(out / "site_manifest.json", json.dumps(manifest, ensure_ascii=False, indent=2))
    write_text(out / ".nojekyll", "")
    print(f"Built {len(overall)} player pages in: {out.resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
